# Generated by Django 5.0.6 on 2024-08-17 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=50)),
                ('Complications', models.TextField(default='', max_length=50)),
                ('How_to_use', models.CharField(default='', max_length=50)),
                ('expiration_date', models.DateTimeField()),
                ('Production_date', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('Medication_type', models.CharField(choices=[('pill', ' pill'), ('Sherbet', ' Sherbet'), ('serum', ' serum'), ('ampoule', ' ampoule'), ('powder', ' powder')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('Medical_license_number', models.CharField(default='', max_length=5)),
                ('Expertise', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('marital_status', models.CharField(choices=[('single', ' single'), ('married', ' married')], default='', max_length=20)),
                ('gender', models.CharField(choices=[('man', ' man'), ('woman', ' woman')], default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('National_code', models.CharField(default='', max_length=10)),
                ('underlying_disease', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('marital_status', models.CharField(choices=[('single', ' single'), ('married', ' married')], default='', max_length=20)),
                ('gender', models.CharField(choices=[('man', ' man'), ('woman', ' woman')], default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=30)),
                ('disease', models.CharField(default='', max_length=30)),
                ('descriptien', models.CharField(default='', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.DateField(auto_now_add=True)),
                ('type_of_disease', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AddPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('Medical_license_number', models.CharField(default='', max_length=5)),
                ('Expertise', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('marital_status', models.CharField(choices=[('single', ' single'), ('married', ' married')], default='', max_length=20)),
                ('gender', models.CharField(choices=[('man', ' man'), ('woman', ' woman')], default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
